#!/usr/bin/env bash
set -euo pipefail

# Generate HTML coverage reports for fuzz targets.
#
# Usage:
#   ./fuzzing/coverage.sh                       # all targets
#   ./fuzzing/coverage.sh fuzz_invariants        # one target
#
# Prerequisites:
#   - Requires nightly toolchain with llvm-tools-preview
#   - Requires cargo-fuzz and rustfilt (auto-installed if missing)
#   - Run fuzz targets first to build a corpus (coverage uses fuzz/corpus/<target>/)
#
# Output:
#   fuzzing/coverage-report/<target>/index.html  — per-target HTML reports

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FUZZ_ENV="$SCRIPT_DIR/.fuzz-env"
COVERAGE_DIR="$SCRIPT_DIR/coverage-report"

export RUSTUP_HOME="$FUZZ_ENV/rustup"
export CARGO_HOME="$FUZZ_ENV/cargo"
export PATH="$CARGO_HOME/bin:$PATH"

ALL_TARGETS=(
    fuzz_tool_call_parsers
    fuzz_parser_configs
    fuzz_reasoning_parsers
    fuzz_streaming_reasoning
    fuzz_detect_start
    fuzz_end_positions
    fuzz_deepseek_parsers
    fuzz_structured_configs
    fuzz_nested_and_large
    fuzz_invariants
    fuzz_differential
    fuzz_redos
    fuzz_with_tools
)

# Ensure toolchain and components
if [ ! -f "$CARGO_HOME/bin/rustup" ]; then
    echo "=== Installing rustup (isolated)..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --default-toolchain nightly
fi
if ! rustup toolchain list | grep -q nightly; then
    rustup install nightly
fi
rustup +nightly component add llvm-tools-preview 2>/dev/null || true
if ! command -v cargo-fuzz &>/dev/null; then
    cargo +nightly install cargo-fuzz
fi

# Select targets
if [ $# -gt 0 ]; then
    TARGETS=("$@")
else
    TARGETS=("${ALL_TARGETS[@]}")
fi

cd "$REPO_ROOT/lib/parsers"

mkdir -p "$COVERAGE_DIR"

for target in "${TARGETS[@]}"; do
    corpus_dir="fuzz/corpus/$target"
    if [ ! -d "$corpus_dir" ] || [ "$(find "$corpus_dir" -maxdepth 1 -type f 2>/dev/null | wc -l | tr -d ' ')" -eq 0 ]; then
        echo "=== [$target] No corpus found — skipping (run the fuzzer first)"
        continue
    fi

    echo "=== [$target] Generating coverage data..."
    cargo +nightly fuzz coverage "$target" 2>&1 || {
        echo "=== [$target] cargo fuzz coverage failed, skipping"
        continue
    }

    # Find the profraw/profdata files generated by cargo-fuzz
    FUZZ_BUILD_DIR="fuzz/coverage/$target"
    if [ ! -d "$FUZZ_BUILD_DIR" ]; then
        echo "=== [$target] No coverage output directory found, skipping"
        continue
    fi

    # Locate the coverage binary
    COVERAGE_BIN=$(find "target" -path "*/coverage/*/$target" -type f -executable 2>/dev/null | head -1)
    PROFDATA=$(find "$FUZZ_BUILD_DIR" -name "*.profdata" 2>/dev/null | head -1)

    if [ -z "$COVERAGE_BIN" ] || [ -z "$PROFDATA" ]; then
        echo "=== [$target] Could not find coverage binary or profdata, skipping"
        continue
    fi

    # Find llvm-cov from the nightly toolchain
    LLVM_COV=$(find "$RUSTUP_HOME" -name "llvm-cov" -type f 2>/dev/null | head -1)
    if [ -z "$LLVM_COV" ]; then
        echo "=== [$target] llvm-cov not found — install llvm-tools-preview"
        continue
    fi

    TARGET_REPORT_DIR="$COVERAGE_DIR/$target"
    mkdir -p "$TARGET_REPORT_DIR"

    echo "=== [$target] Generating HTML report..."
    "$LLVM_COV" show "$COVERAGE_BIN" \
        --instr-profile="$PROFDATA" \
        --format=html \
        --output-dir="$TARGET_REPORT_DIR" \
        --ignore-filename-regex='/.cargo/|/rustc/|fuzz_targets/' \
        2>&1 || echo "=== [$target] llvm-cov show failed"

    echo "=== [$target] Report: $TARGET_REPORT_DIR/index.html"
done

echo ""
echo "=== Coverage reports: $COVERAGE_DIR/"
